services:
  frontend:
    build:
      context: ./frontend
      target: production
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: production
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://eventhub:eventhub_dev@postgres:5432/eventhub
      MONGO_URL: mongodb://mongo:27017/eventhub
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - mongo
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: eventhub_dev
      POSTGRES_DB: eventhub
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    volumes:
      - mongo_prod_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_prod_data:
  mongo_prod_data:
